## Support This Project ❤️

If this credit risk analysis tool has helped you with your financial modeling or risk assessment projects, consider supporting its development:

- ☕ [Buy me a coffee](https://coff.ee/vincentkirui)
- 📱 M-Pesa: [0799476072]

Your support helps maintain and improve this open-source financial tool!
